protected/models/Links.php
<?php

class Links extends ActiveRecord
{
    public $rulesOptions
        = array(
            'name' => array(
                'maxlength' => 32,
                'autocomplete' => 'off',
                'autofocus' => 'autofocus',
                'placeholder' => 'Например: Товар из сельхоз магазина'

            ),
            'url' => array(
                'maxlength' => 253,
                'autocomplete' => 'on',
                'placeholder' => 'Например: http://example.com/'
            ),
        );

    public function tableName()
    {
        return 'links';
    }

    public function rules()
    {
        return array(
            array('name, url', 'required', 'message' => 'Поле не может быть пустым'),
            array('name', 'length', 'min' => 2, 'tooShort' => 'Минимальная длина 2 символа'),
            array('name', 'length', 'max' => 32, 'tooLong' => 'Максимальная длина 32 символа'),
            array('url', 'length', 'min' => 5, 'tooShort' => 'Минимальная длина 5 символов'),
            array('url', 'length', 'max' => 253, 'tooLong' => 'Максимальная длина 253 символа'),
            array('url', 'url', 'message' => 'Поле должно содержать ссылку'),
            array('id, name, url', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'clicks' => array(self::HAS_MANY, 'Clicks', 'rule_id'),
            'events' => array(self::HAS_MANY, 'Events', 'rule_id'),
            'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
            'rules' => array(self::HAS_MANY, 'RulesUrl', 'link_id'),
        );
    }

    public function attributeLabels()
    {
        return array('name' => 'Наименование', 'url' => 'Ссылка');
    }

    public function search()
    {
        $criteria = new CDbCriteria;
        $criteria->select = 't.id, t.name, t.url';
        $criteria->compare('user_id', Yii::app()->user->id);
        $criteria->compare('t.name', $this->name, true);
        $criteria->compare('t.url', $this->url, true);
        $criteria->order = 't.id DESC';
        $dep = new CDbCacheDependency('SELECT MAX(id) FROM links');
        $model = self::model()->cache(self::$duration, $dep, 1);

        return new CActiveDataProvider($model, array('criteria' => $criteria, 'pagination' => $this->pagination));
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function scopes()
    {
        $condition = 'user_id=' . Yii::app()->user->id;

        return array(
            'select' => array('select' => 'id, name', 'condition' => $condition),
            'self' => array('select' => 'id, user_id, name, url', 'condition' => $condition),
            'countSelf' => array('select' => 'COUNT(id) as id', 'condition' => $condition)
        );
    }

    public function beforeDelete()
    {

        $criteria = new CDbCriteria();
        $criteria->compare('link_id', $this->id);
        Clicks::model()->deleteAll($criteria);
        Events::model()->deleteAll($criteria);
        RulesUrl::model()->deleteAll($criteria);

        return true;
    }

    public function beforeSave()
    {
        $this->user_id = Yii::app()->user->id;

        return true;
    }

    public static function  getDropDown()
    {
        $dep = new CDbCacheDependency('SELECT MAX(id) FROM links');
        $model = self::model()->cache(self::$duration, $dep, 1)->select()->findAll();

        return CHtml::listData($model, 'id', 'name');
    }

    public function urlEncode()
    {
        return CHtml::link($this->url, $this->url, array('target' => '_blank'));
    }
}

protected/controllers/LinksController.php
<?php

class LinksController extends Controller
{

    public $name = 'Ссылки';

    public function filters()
    {
        return array('accessControl', 'postOnly + delete');
    }

    public function accessRules()
    {
        return array(
            array('allow', 'actions' => array('index', 'create', 'update', 'delete', 'view'), 'users' => array('@')),
            array('deny', 'users' => array('*'))
        );
    }

    protected function loadModel($id)
    {
        $model = Links::model()->self()->findByPk($id);
        if ($model === null) {
            throw new CHttpException(404, 'Страница не найдена.');
        }

        return $model;
    }

    public function actionIndex()
    {
        $this->title = $this->name;
        $model = new Links('search');
        $model->unsetAttributes();
        if (isset($_GET['Links'])) {
            $model->attributes = $_GET['Links'];
        }
        $this->breadcrumbs = array($this->name);
        $this->render('index', array('model' => $model));
    }

    public function actionCreate()
    {
        $this->title = $this->name . ' - Добавить';
        $model = new Links;
        if (isset($_POST['Links'])) {
            $model->attributes = $_POST['Links'];
            if ($model->save()) {
                $this->redirect(array('index'));
            }
        }
        $this->breadcrumbs = array($this->name => array('/links'), 'Добавить');
        $this->render('_form', array('model' => $model));
    }

    public function actionUpdate($id)
    {
        $this->title = $this->name . ' - Редактировать';
        $model = $this->loadModel($id);
        if (isset($_POST['Links'])) {
            $model->attributes = $_POST['Links'];
            if ($model->save()) {
                $this->redirect(array('index'));
            }
        }
        $this->breadcrumbs = array($this->name => array('/links'), 'Редактировать');
        $this->render('_form', array('model' => $model));
    }

    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();
        if (!isset($_GET['ajax'])) {
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        }
    }

    public function actionView($id)
    {
        $this->title = $this->name . ' - Просмотр';
        $model = $this->loadModel($id);
        $clicks = new Clicks('search');
        $clicks->unsetAttributes();
        $clicks->link_id = $id;
        if (isset($_GET['Clicks'])) {
            $clicks->attributes = $_GET['Clicks'];
        }
        $this->breadcrumbs = array($this->name => array('/links'), 'Просмотр');
        $this->render('view', array('model' => $model, 'clicks' => $clicks));
    }
}

protected/views/links/_form.php
<div class="row">
    <div class="col-xs-5">
        <h3><?php echo $model->getAction(); ?></h3>
        <?php if (!empty($model->errors)): ?>
            <?php $this->renderPartial('//layouts/_alert_errors'); ?>
        <?php endif; ?>
        <?php $form = $this->beginWidget('CActiveForm', array('id' => 'links')); ?>
        <div class="form-group <?php echo $form->error($model, 'name') ? 'has-error' : ''; ?>">
            <?php echo $form->labelEx($model, 'name', $model->htmlOptions['label']); ?>
            <?php echo $form->textField($model, 'name', $model->mergeOptions('input', 'name')); ?>
            <span class="text-danger"><?php echo $form->error($model, 'name'); ?></span>
        </div>
        <div class="form-group <?php echo $form->error($model, 'url') ? 'has-error' : ''; ?>">
            <?php echo $form->labelEx($model, 'url', $model->htmlOptions['label']); ?>
            <?php echo $form->textField($model, 'url', $model->mergeOptions('input', 'url')); ?>
            <span class="text-danger"> <?php echo $form->error($model, 'url'); ?></span>
        </div>
        <hr/>
        <p class="help-block">
            <small>Поля с * - обязательные для заполнения.</small>
        </p>
        <div class="form-group btn-group pull-right">
            <?php echo CHtml::link('Отмена', Yii::app()->createUrl('links'), $model->htmlOptions['cancelButton']); ?>
            <?php echo CHtml::submitButton($model->getAction(), $model->htmlOptions['submitButton']); ?>
        </div>
        <?php $this->endWidget(); ?>
    </div>
</div>

protected/views/links/index.php
<?php echo CHtml::link('Добавить', Yii::app()->createUrl('links/create'), array('class' => 'btn btn-default btn-sm')); ?>
    <p class="btn help-block ">Внимание! Удаление ссылки, повлияет на статистику по переходам.</p>
<?php
$this->widget(
    'zii.widgets.grid.CGridView', array(
        'id' => 'links-grid',
        'dataProvider' => $model->search(),
        'filter' => $model,
        'enableSorting' => false,
        'columns' => array(
            array(
                'name' => 'name',
                'filter' => CHtml::activeTextField($model, 'name', array('placeholder' => ' Поиск по Наименованию...'))
            ),
            array(
                'name' => 'url',
                'filter' => CHtml::activeTextField($model, 'url', array('placeholder' => ' Поиск по ссылке...')),
                'value' => '$data->urlEncode()',
                'type' => 'raw'
            ),
            array(
                'class' => 'CButtonColumn',
                'template' => '<div class="btn-group">{view}{update}{delete}</div>',
                'htmlOptions' => array('class' => 'text-center', 'style' => 'width:150px;'),
                'header' => 'Действия',
                'updateButtonImageUrl' => false,
                'viewButtonImageUrl' => false,
                'deleteButtonImageUrl' => false,
                'deleteConfirmation' => 'Вы действительно хотите удалить ссылку?',
                'deleteButtonOptions' => array(
                    'class' => 'btn btn-sm btn-default delete',
                    'title' => 'Удалить'
                ),
                'updateButtonOptions' => array(
                    'class' => 'btn btn-sm btn-default',
                    'title' => 'Редактировать'
                ),

                'viewButtonOptions' => array(
                    'class' => 'btn btn-sm btn-default',
                    'title' => 'Просмотр'
                ),
                'buttons' => array(
                    'update' => array('label' => '<span class="glyphicon glyphicon-pencil"></span>'),
                    'delete' => array('label' => '<span class="glyphicon glyphicon-trash"></span>'),
                    'view' => array('label' => '<span class="glyphicon glyphicon-eye-open"></span>')
                ),
            ),
        ),
    )
);

protected/views/links/view.php
<?php

$this->widget(
    'zii.widgets.CDetailView', array(
        'data' => $model, 'attributes' => array(
            array(
                'name' => 'name'
            ),
            array(
                'name' => 'url',
                'value' => $model->urlEncode(),
                'type' => 'raw'
            )
        )
    )
);

$this->widget(
    'zii.widgets.grid.CGridView', array(
        'id' => 'clicks-grid',
        'dataProvider' => $clicks->search(),
        'enableSorting' => false,
        'filter' => $clicks,
        'columns' => array(
            array(
                'name' => 'ip',
                'value' => '$data->getIp()',
                'type' => 'raw',
                'filter' => CHtml::activeTextField($clicks, 'ip', array('placeholder' => ' Поиск...')),
                'htmlOptions' => array('style' => 'width:10%'),
            ),
            array(
                'name' => 'rule_id',
                'value' => '$data->rule->name',
                'filter' => RulesUrl::getDropDown(),
                'htmlOptions' => array('style' => 'width:10%'),
            ),
            array(
                'name' => 'refer_id',
                'filter' => Refers::getDropDown(),
                'value' => '$data->refer->url',
            ),
            array(
                'name' => 'os_id',
                'value' => '$data->os->name',
                'filter' => Oses::getDropDown(),
                'htmlOptions' => array('style' => 'width:8%'),
            ),
            array(
                'name' => 'browser_id',
                'value' => '$data->browser->name',
                'filter' => Browsers::getDropDown(),
                'htmlOptions' => array('style' => 'width:8%'),
            ),
            array(
                'name' => 'device_type',
                'value' => '$data->getDevice()',
                'filter' => $clicks->devices,
                'htmlOptions' => array('style' => 'width:7%'),
            ),
            array(
                'name' => 'order',
                'value' => '$data->getBoolean($data->order)',
                'filter' => $clicks->booleans,
                'type'=>'raw',
                'htmlOptions' => array('style' => 'width:7%', 'class'=>'text-center'),
            ),
            array(
                'name' => 'is_bot',
                'value' => '$data->getBoolean($data->is_bot)',
                'filter' => $clicks->booleans,
                'type'=>'raw',
                'htmlOptions' => array('style' => 'width:5%', 'class'=>'text-center'),
            ),
            array(
                'name' => 'created',
                'filter' => $this->widget(
                        'zii.widgets.jui.CJuiDatePicker',
                        array('model' => $clicks, 'attribute' => 'created'), true
                    ),
                'htmlOptions' => array('style' => 'width:12%'),
            ),
            array(
                'name' => 'geo_ip_ip_range_id',
                'value' => '$data->geo()',
                'filter' => false,
                'htmlOptions' => array('style' => 'width:10%'),
            ),
        ),
    )
);