protected/controllers/RulesController.php
<?php

class RulesController extends Controller
{

    public $name = 'Правила';

    public function filters()
    {
        return array('accessControl', 'postOnly + delete');
    }

    public function accessRules()
    {
        return array(
            array('allow', 'actions' => array('index', 'view', 'create', 'update', 'delete'), 'users' => array('@')),
            array('deny', 'users' => array('*'))
        );
    }

    protected function loadModel($id)
    {
        $model = RulesUrl::model()->self()->findByPk($id);
        if ($model === null) {
            throw new CHttpException(404, 'Страница не найдена.');
        }

        return $model;
    }

    public function actionIndex()
    {
        $this->title = $this->name . ' - [администрирование]';
        $model = new RulesUrl('search');
        $model->unsetAttributes();
        if (isset($_GET['RulesUrl'])) {
            $model->attributes = $_GET['RulesUrl'];
        }
        $this->breadcrumbs = array($this->name);
        $this->render('index', array('model' => $model));
    }

    public function actionView($id)
    {
        $this->title = $this->name . ' - [просмотр]';
        $model = $this->loadModel($id);
        $clicks = new Clicks('search');
        $clicks->unsetAttributes();
        $clicks->rule_id = $id;
        if (isset($_GET['Clicks'])) {
            $clicks->attributes = $_GET['Clicks'];
        }
        $this->breadcrumbs = array($this->name => array('/rules'), 'Просмотр');
        $this->render('view', array('model' => $model, 'clicks' => $clicks));
    }

    public function actionCreate()
    {
        $this->title = $this->name . ' - [добавить]';
        $model = new RulesUrl;
        $model->categories = Categories::getDropDown();
        $model->links = Links::getDropDown();
        if (isset($_POST['RulesUrl'])) {
            $model->attributes = $_POST['RulesUrl'];
            if ($model->save()) {
                $model->token = Hash::work()->generate($model->id);
                $model->save();
                $this->redirect(array('index'));
            }
        }
        $this->breadcrumbs = array($this->name => array('/rules'), 'Добавить');
        $this->render('_form', array('model' => $model));
    }

    public function actionUpdate($id)
    {
        $this->title = $this->name . ' - [изменить]';
        $model = $this->loadModel($id);
        $model->categories = Categories::getDropDown();
        $model->links = Links::getDropDown();
        if (isset($_POST['RulesUrl'])) {
            $model->attributes = $_POST['RulesUrl'];
            if ($model->save()) {
                $model->token = Hash::work()->generate($model->id);
                $model->save();
                $this->redirect(array('index'));
            }
        }
        $this->breadcrumbs = array($this->name => array('/rules'), 'Изменить');
        $this->render('_form', array('model' => $model));
    }

    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();
        if (!isset($_GET['ajax'])) {
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        }
    }
}

protected/views/rules/_form.php
<div class="row">
    <div class="col-xs-5">
        <h3><?php echo $model->getAction(); ?></h3>
        <?php if (!empty($model->errors)): ?>
            <?php $this->renderPartial('//layouts/_alert_errors'); ?>
        <?php endif; ?>
        <?php $form = $this->beginWidget('CActiveForm', array('id' => 'rules-form')); ?>
        <div class="form-group <?php echo $form->error($model, 'name') ? 'has-error' : ''; ?>">
            <?php echo $form->labelEx($model, 'name', $model->htmlOptions['label']); ?>
            <?php echo $form->textField($model, 'name', $model->mergeOptions('input', 'name')); ?>
            <span class="text-danger"> <?php echo $form->error($model, 'name'); ?></span>
        </div>
        <div class="form-group <?php echo $form->error($model, 'category_id') ? 'has-error' : ''; ?>">
            <?php echo $form->labelEx($model, 'category_id', $model->htmlOptions['label']); ?>
            <?php echo $form->dropDownList(
                $model, 'category_id', $model->categories, $model->mergeOptions('input', 'category_id')
            ); ?>
            <span class="text-danger"> <?php echo $form->error($model, 'category_id'); ?></span>
        </div>
        <div class="form-group <?php echo $form->error($model, 'link_id') ? 'has-error' : ''; ?>">
            <?php echo $form->labelEx($model, 'link_id', $model->htmlOptions['label']); ?>
            <?php echo $form->dropDownList(
                $model, 'link_id', $model->links, $model->mergeOptions('input', 'link_id')
            ); ?>
            <span class="text-danger"> <?php echo $form->error($model, 'link_id'); ?></span>
        </div>
        <div class="checkbox">
            <label><?php echo $form->checkBox($model, 'status'); ?> В работе</label>
            <span class="text-danger"> <?php echo $form->error($model, 'status'); ?></span>
        </div>
        <hr/>
        <p class="help-block"><small>Поля с * - обязательные для заполнения.</small></p>
        <div class="form-group btn-group pull-right">
            <?php echo CHtml::link('Отмена', Yii::app()->createUrl('rules'), $model->htmlOptions['cancelButton']); ?>
            <?php echo CHtml::submitButton($model->getAction(), $model->htmlOptions['submitButton']); ?>
        </div>
        <?php $this->endWidget(); ?>
    </div>
</div>

protected/views/rules/index.php
<?php echo CHtml::link('Добавить', Yii::app()->createUrl('rules/create'), array('class' => 'btn btn-default btn-sm')); ?>
    <p class="btn help-block ">Внимание! Удаление правила, повлияет на статистику по переходам.</p>
<?php
$this->widget(
    'zii.widgets.grid.CGridView', array(
        'id' => 'rules-grid',
        'dataProvider' => $model->search(),
        'enableSorting' => false,
        'filter' => $model,
        'columns' => array(
            array(
                'name' => 'name',
                'filter' => CHtml::activeTextField(
                        $model, 'name', array('placeholder' => ' Поиск по наименованию...')
                    )
            ),
            array('name' => 'category_id', 'value' => '$data->category->name', 'filter' => Categories::getDropDown()),
            array('name' => 'link_id', 'value' => '$data->link->name', 'filter' => Links::getDropDown()),
            array(
                'name' => 'status',
                'value' => '$data->getStatus()',
                'type' => 'raw',
                'filter' => $model::$statuses,
                'htmlOptions' => array('class' => 'text-center')
            ),
            array('name' => 'token', 'value' => '$data->urlEncode()', 'type' => 'raw', 'filter' => false),
            array(
                'class' => 'CButtonColumn',
                'template' => '<div class="btn-group">{view}{update}{delete}</div>',
                'htmlOptions' => array('class' => 'text-center', 'style' => 'width:120px;'),
                'header' => 'Действия',
                'updateButtonImageUrl' => false,
                'viewButtonImageUrl' => false,
                'deleteButtonImageUrl' => false,
                'deleteConfirmation' => 'Вы действительно хотите удалить правило?',
                'deleteButtonOptions' => array(
                    'class' => 'btn btn-sm btn-default delete',
                    'title' => 'Удалить'
                ),
                'updateButtonOptions' => array(
                    'class' => 'btn btn-sm btn-default',
                    'title' => 'Редактировать'
                ),

                'viewButtonOptions' => array(
                    'class' => 'btn btn-sm btn-default',
                    'title' => 'Просмотр'
                ),
                'buttons' => array(
                    'update' => array('label' => '<span class="glyphicon glyphicon-pencil"></span>'),
                    'delete' => array('label' => '<span class="glyphicon glyphicon-trash"></span>'),
                    'view' => array('label' => '<span class="glyphicon glyphicon-eye-open"></span>')
                ),
            ),
        ),
    )
);

protected/views/rules/view.php
<?php

$this->widget(
    'zii.widgets.CDetailView', array(
        'data' => $model,
        'attributes' => array(
            array('name' => 'name'),
            array('name' => 'category_id', 'value' => $model->category->name),
            array('name' => 'link_id', 'value' => $model->link->name),
            array('name' => 'token', 'value' => $model->urlEncode(), 'type' => 'raw'),
            array('name' => 'status', 'value' => $model->getStatus(), 'type' => 'raw'),
        ),
    )
);

$this->widget(
    'zii.widgets.grid.CGridView', array(
        'id' => 'clicks-grid',
        'dataProvider' => $clicks->search(),
        'enableSorting' => false,
        'filter' => $clicks,
        'columns' => array(
            array(
                'name' => 'ip',
                'value' => '$data->getIp()',
                'type' => 'raw',
                'filter' => CHtml::activeTextField($clicks, 'ip', array('placeholder' => ' Поиск...')),
                'htmlOptions' => array('style' => 'width:10%'),
            ),
            array(
                'name' => 'link_id',
                'value' => '$data->link->name',
                'filter' => Links::getDropDown(),
                'htmlOptions' => array('style' => 'width:10%'),
            ),
            array(
                'name' => 'refer_id',
                'filter' => Refers::getDropDown(),
                'value' => '$data->refer->url',
            ),
            array(
                'name' => 'os_id',
                'value' => '$data->os->name',
                'filter' => Oses::getDropDown(),
                'htmlOptions' => array('style' => 'width:8%'),
            ),
            array(
                'name' => 'browser_id',
                'value' => '$data->browser->name',
                'filter' => Browsers::getDropDown(),
                'htmlOptions' => array('style' => 'width:8%'),
            ),
            array(
                'name' => 'device_type',
                'value' => '$data->getDevice()',
                'filter' => $clicks->devices,
                'htmlOptions' => array('style' => 'width:7%'),
            ),
            array(
                'name' => 'order',
                'value' => '$data->getBoolean($data->order)',
                'filter' => $clicks->booleans,
                'type' => 'raw',
                'htmlOptions' => array('style' => 'width:7%', 'class' => 'text-center'),
            ),
            array(
                'name' => 'is_bot',
                'value' => '$data->getBoolean($data->is_bot)',
                'filter' => $clicks->booleans,
                'type' => 'raw',
                'htmlOptions' => array('style' => 'width:5%', 'class' => 'text-center'),
            ),
            array(
                'name' => 'created',
                'filter' => $this->widget(
                        'zii.widgets.jui.CJuiDatePicker',
                        array('model' => $clicks, 'attribute' => 'created'), true
                    ),
                'htmlOptions' => array('style' => 'width:12%'),
            ),
            array(
                'name' => 'geo_ip_ip_range_id',
                'value' => '$data->geo()',
                'filter' => false,
                'htmlOptions' => array('style' => 'width:10%'),
            ),
        ),
    )
);