protected/controllers/CategoriesController.php
<?php

class CategoriesController extends Controller
{

    public $name = 'Категории';

    public function filters()
    {
        return array('accessControl', 'postOnly + delete');
    }

    public function accessRules()
    {
        return array(
            array('allow', 'actions' => array('index', 'create', 'update'), 'users' => array('@')),
            array('deny', 'users' => array('*'))
        );
    }

    protected function loadModel($id)
    {
        $model = Categories::model()->self()->findByPk($id);
        if ($model === null) {
            throw new CHttpException(404, 'Страница не найдена.');
        }

        return $model;
    }

    public function actionIndex()
    {
        $this->title = $this->name;
        $model = new Categories('search');
        $model->unsetAttributes();
        if (isset($_GET['Categories'])) {
            $model->attributes = $_GET['Categories'];
        }
        $this->breadcrumbs = array($this->name);
        $this->render('index', array('model' => $model));
    }

    public function actionCreate()
    {
        $this->title = $this->name . ' - Добавить';
        $model = new Categories;
        if (isset($_POST['Categories'])) {
            $model->attributes = $_POST['Categories'];
            if ($model->save()) {
                $this->redirect(array('index'));
            }
        }
        $this->breadcrumbs = array($this->name => array('/categories'), 'Добавить');
        $this->render('_form', array('model' => $model));
    }

    public function actionUpdate($id)
    {
        $this->title = $this->name . ' - редактировать';
        $model = $this->loadModel($id);
        if (isset($_POST['Categories'])) {
            $model->attributes = $_POST['Categories'];
            if ($model->save()) {
                $this->redirect(array('index'));
            }
        }
        $this->breadcrumbs = array($this->name => array('/categories'), 'Редактировать');
        $this->render('_form', array('model' => $model));
    }
}

protected/views/categories/_form.php
<div class="row">
    <div class="col-xs-5">
        <h3><?php echo $model->getAction(); ?></h3>
        <?php if (!empty($model->errors)): ?>
            <?php $this->renderPartial('//layouts/_alert_errors'); ?>
        <?php endif; ?>
        <?php $form = $this->beginWidget('CActiveForm', array('id' => 'categories')); ?>
        <div class="form-group <?php echo $form->error($model, 'name') ? 'has-error' : ''; ?>">
            <?php echo $form->labelEx($model, 'name', $model->htmlOptions['label']); ?>
            <?php echo $form->textField($model, 'name', $model->mergeOptions('input', 'name')); ?>
            <span class="text-danger"> <?php echo $form->error($model, 'name'); ?></span>
        </div>
        <hr/>
        <p class="help-block"><small>Поля с * - обязательные для заполнения.</small></p>
        <div class="form-group btn-group pull-right">
            <?php echo CHtml::link('Отмена', Yii::app()->createUrl('categories'), $model->htmlOptions['cancelButton']); ?>
            <?php echo CHtml::submitButton($model->getAction(), $model->htmlOptions['submitButton']); ?>
        </div>
        <?php $this->endWidget(); ?>
    </div>
</div>

protected/views/categories/index.php
<?php echo CHtml::link('Добавить', Yii::app()->createUrl('categories/create'), array('class' => 'btn btn-default btn-sm')); ?>
<?php
$this->widget(
    'zii.widgets.grid.CGridView', array(
        'id' => 'categories-grid',
        'dataProvider' => $model->search(),
        'filter' => $model,
        'enableSorting' => false,
        'columns' => array(
            array(
                'name' => 'name',
                'filter' => CHtml::activeTextField($model, 'name', array('placeholder' => ' Поиск по категории...'))
            ),
            array(
                'class' => 'CButtonColumn',
                'template' => '<div class="btn-group">{update}</div>',
                'htmlOptions' => array('style' => 'width:120px;', 'class' => 'text-center'),
                'header' => 'Действия',
                'updateButtonImageUrl' => false,
                'updateButtonOptions' => array(
                    'class' => 'btn btn-sm btn-default',
                    'title' => 'Редактировать'
                ),
                'buttons' => array(
                    'update' => array('label' => '<span class="glyphicon glyphicon-pencil"></span>'),
                ),
            ),
        ),
    )
);